version: "3.9"

services:
  StudyGroup-db:
    container_name: StudyGroup-db
    image: "postgres:15.3-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5448:5432"
    volumes:
      - StudyGroup-db-postgres-volume:/var/lib/postgresql/data

volumes:
  StudyGroup-db-postgres-volume: